## Phase 1: NumPy Basics

### Q1. Create a NumPy array from a Python list  




In [2]:
import numpy as np

arr = np.array([10, 20, 30, 40])
print(arr)
print(type(arr))


[10 20 30 40]
<class 'numpy.ndarray'>


## Q2. Create a NumPy array using arange()
Create an array from 1 to 10.


In [3]:
np.arange(1, 11)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Q3. Create an array of zeros and ones

Create an array of 5 zeros

Create an array of 5 ones

In [4]:
zeros_array = np.zeros(5)
ones_array = np.ones(5)

print("Array of zeros:", zeros_array)
print("Array of ones:", ones_array)

Array of zeros: [0. 0. 0. 0. 0.]
Array of ones: [1. 1. 1. 1. 1.]


## Q4. Check array properties

### For array [1, 2, 3, 4, 5], find:

shape

size

dtype

In [5]:
arr = np.array([1, 2, 3, 4, 5])

print("Array:", arr)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data type:", arr.dtype)

Array: [1 2 3 4 5]
Shape: (5,)
Size: 5
Data type: int64


## Q5. Convert float array to integer

In [6]:
arr = np.array([1.2, 2.5, 3.8])
arr.astype(int)


array([1, 2, 3])

## List vs Numpy Array


In [11]:
import time
start= time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ",time.time() - start)

start= time.time()
np_array= np.arange(1000000)*2
print("\n Numpy operation time: ", time.time() -start)


py_list= [1, 2, 3]
print("Python list multiplication: ", py_list*2)

np_array= np.array([1, 2, 3])
print("Python Array multiplication: ",np_array*2)


 List operation time:  0.0420379638671875

 Numpy operation time:  0.0007891654968261719
Python list multiplication:  [1, 2, 3, 1, 2, 3]
Python Array multiplication:  [2 4 6]


## Vector, Matrix And Tensor


In [12]:
vector = np.array([2,4,6])
print("Vector: ",vector)

matrix = np.array([[2,4,6],[1,3,5]])
print("matrix: ",matrix)

tensor= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("Tensor: ",tensor)



Vector:  [2 4 6]
matrix:  [[2 4 6]
 [1 3 5]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array Reshaping


In [17]:
arr = np.arange(12)
print("Original array", arr)

reshaped = arr.reshape((3,4))
print("\n reshaped array", reshaped)

flattened = reshaped.flatten()
print("\n  flattened array", flattened )

#  Ravel(retrurns view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array", raveled )



Original array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

  flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]
