## Phase: 2 Numpy Array operations

In [1]:
import numpy as np
np.__version__

'2.4.2'

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic slicing: ", arr[2:7])

Basic slicing:  [3 4 5 6 7]


### Create 2D Array

In [4]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Specific elemet: ",arr_2d[1,2])
print("Entire row: ",arr_2d[1])


Specific elemet:  6
Entire row:  [4 5 6]


## Sorting


In [10]:
unsorted = np.array([4,1,2,5,6,3,9])
print("Sorted array: ",np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1], [1,2], [2, 3]])
print("Sorted 2D array by column: ", np.sort(arr_2d_unsorted, axis=1))


Sorted array:  [1 2 3 4 5 6 9]
Sorted 2D array by column:  [[1 3]
 [1 2]
 [2 3]]


## Mathematical Operations

In [11]:
a = np.array([1,2,3])
b = np.array([4,5,6])

a + b, a - b, a * b


(array([5, 7, 9]), array([-3, -3, -3]), array([ 4, 10, 18]))

## Mathematical functions

In [12]:
arr = np.array([1, 4, 9, 16])

np.sqrt(arr), np.mean(arr), np.sum(arr)


(array([1., 2., 3., 4.]), np.float64(7.5), np.int64(30))

## Min, max, index

In [13]:
arr = np.array([10, 45, 23, 89, 12])

np.max(arr), np.min(arr), np.argmax(arr)


(np.int64(89), np.int64(10), np.int64(3))

## Filter values

In [14]:
arr = np.array([10, 25, 30, 5, 40, 15])

arr[arr > 20]


array([25, 30, 40])

### Even Numbers

In [15]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]
print("Even Numbers: ",even_number)

Even Numbers:  [ 2  4  6  8 10]


## Filter with mask


In [16]:
mask = numbers>5
print("Numbers greater than 5",numbers[mask])

Numbers greater than 5 [ 6  7  8  9 10]


## Fancy Indexing vs np.where()

In [20]:
indices = [0,2,4]
print(numbers[indices])

where_result= np.where(numbers>5)
print(where_result)
print("NP Where ", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP Where  [ 6  7  8  9 10]


In [21]:
condition_array = np.where(numbers>5, numbers*4, numbers)
print(condition_array)

[ 1  2  3  4  5 24 28 32 36 40]


## Adding and Removing Array

In [22]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


### Array Compatibility


In [25]:
a = np.array([1,2,3,4])
b = np.array([3,2,3,5])
c = np.array([7,6,5,4,7])
print("Compatibility shapes", a.shape == b.shape)
print("Compatibility shapes", a.shape == c.shape)

Compatibility shapes True
Compatibility shapes False


### Array Addition

In [28]:
original = np.array([[1,2,],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original, new_row))
print("original array: ", original)
print("New_array: ", with_new_row)

new_col = np.array([[6],[7]])
with_new_col = np.hstack((original, new_col))
print("New column added: ", with_new_row)




original array:  [[1 2]
 [3 4]]
New_array:  [[1 2]
 [3 4]
 [5 6]]
New column added:  [[1 2]
 [3 4]
 [5 6]]


### Array deletion

In [29]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print("Array after deletion:",deleted)

Array after deletion: [1 2 4 5]
